### ISSUE TITLE
Lỗi kết nối Hass với loa Maika

### ISSUE THREAD

**Issue by dieplaichaupost** [olli-ai/maika_assistant#18]
![image](https://github.com/olli-ai/maika_assistant/assets/28680186/faa429c2-8643-4153-9e8d-73d2db6fd2ab)

**Comment by dieplaichaupost** [comment]
![image](https://github.com/olli-ai/maika_assistant/assets/28680186/a433e1fd-a50d-4a0e-923b-b86316ed4ee4)

**Comment by linguyen1511** [comment]
http://localhost:8123 bạn thử lại với URL này xem được không

**Comment by linguyen1511** [comment]
bạn xem thử log lỗi của Hass báo lỗi gì, bạn chép lỗi đó lên mình phân tích thử

**Comment by dieplaichaupost** [comment]
![image](https://github.com/olli-ai/maika_assistant/assets/28680186/323861a6-c7b7-41d5-996b-608a07687742)

**Comment by dieplaichaupost** [comment]
![image](https://github.com/olli-ai/maika_assistant/assets/28680186/396e7c93-fee4-4e9d-a16c-f675892837e3)
Log đây ạ

**Comment by dieplaichaupost** [comment]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/maika_assistant/__init__.py:181
Integration: Maika Assistant (documentation)
First occurred: 08:37:34 (1 occurrences)
Last logged: 08:37:34

Error setting up entry MAIKA for maika_assistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/maika_assistant/__init__.py", line 181, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by dieplaichaupost** [comment]
[home-assistant_2023-05-10T04-11-02.855Z.log](https://github.com/olli-ai/maika_assistant/files/11437986/home-assistant_2023-05-10T04-11-02.855Z.log)

**Comment by linguyen1511** [comment]
version bạn mới hơn version hiện tại, để mình upgrade maika_component lên version tương thích với bản mới nhất

**Comment by linguyen1511** [comment]
Mình mới update rồi nhé bạn @dieplaichaupost

**Comment by dieplaichaupost** [comment]
[home-assistant_2023-05-10T10-32-30.127Z.log](https://github.com/olli-ai/maika_assistant/files/11440835/home-assistant_2023-05-10T10-32-30.127Z.log)

**Comment by linguyen1511** [comment]
vậy đợi mình check lại, rồi báo nhé

**Comment by dieplaichaupost** [comment]
> vậy đợi mình check lại, rồi báo nhé

tình hình sao rồi ad ơi :)

**Comment by linguyen1511** [comment]
mình viết xong mà không test được :(((. Do hiện tại môi trường dev (https://developers.home-assistant.io/docs/development_environment/) của Hass dùng version python > 3.10, mà dùng 3.10 thì lại start script setup bị lỗi, mình lại không có sẵn phần cứng cài Hass để test, bạn đợi thêm ít hôm để mình tìm phần cứng cài Hass mới nhất rồi test

**Comment by dieplaichaupost** [comment]
> mình viết xong mà không test được :(((. Do hiện tại môi trường dev (https://developers.home-assistant.io/docs/development_environment/) của Hass dùng version python > 3.10, mà dùng 3.10 thì lại start script setup bị lỗi, mình lại không có sẵn phần cứng cài Hass để test, bạn đợi thêm ít hôm để mình tìm phần cứng cài Hass mới nhất rồi test

ad cứ up lên để mình download về mình test luôn

**Comment by linguyen1511** [comment]
lỡ không chạy lại mất công push code lên lắm bạn, để mình setup môi trường test cho kỹ

**Comment by linguyen1511** [comment]
bạn dùng thử bản 2023.5.3 mới nhất mình mới push lên nhé
