### ISSUE TITLE
Fix lỗi không nhận diện được thiết bị

### ISSUE THREAD

**Issue by caohuongls** [olli-ai/maika_assistant#3]
This error originated from a custom integration.

Logger: custom_components.maika_assistant.smart_home
Source: helpers/frame.py:73
Integration: Maika Assistant (documentation)
First occurred: 3:01:43 AM (78 occurrences)
Last logged: 3:01:44 AM

Error serializing button.reset_chi_so_chat_luong_khong_khi
Error serializing sensor.thoi_tiet_temperature_2h
Error serializing sensor.thoi_tiet_humidity
Error serializing switch.hass_camera_motion_detection
Error serializing switch.hass_camera_still_images
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 67, in report
    integration_frame = get_integration_frame(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 47, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/maika_assistant/helpers.py", line 573, in sync_serialize
    entity_entry, device_entry = await _get_entity_and_device(
  File "/config/custom_components/maika_assistant/helpers.py", line 55, in _get_entity_and_device
    dev_reg, ent_reg = await gather(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 723, in async_get_registry
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 73, in report
    raise RuntimeError(msg) from err
RuntimeError: Detected code that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report this issue.

**Comment by linguyen1511** [comment]
I just supported new version, it's compatible with new Hass version 2022.6.5, pls help me try this
